playfair: main.o playfair.o
	clang++ -g -Wall main.o playfair.o -o playfair
main.o: main.cpp playfair.h
	clang++ -g -Wall main.cpp -c 
playfair.o: playfair.cpp playfair.cpp
	clang++ -g -Wall playfair.cpp -c